### PR TITLE
Add exchangesda feature at built-in features and API endpoints

### PR DESCRIPTION
**Pull request by wernling-proximax**

### CODE REVIEW

**Review by ynewmann — APPROVED** [review]

**Comment by ynewmann** [comment]
@wernling-proximax  solve conflicts, please

**Review by ynewmann — APPROVED** [review]

**Comment by ynewmann** [comment]
@wernling-proximax Exchange SDA exchange available since version 0.7.2?

**Comment by wernling-proximax** [comment]
@jenyasd209 Based on the source code in the releases, it's available since version 0.9.0.
https://github.com/proximax-storage/js-xpx-chain-rest/releases/tag/release-v0.9.0

**Comment by ynewmann** [comment]
> @jenyasd209 Based on the source code in the releases, it's available since version 0.9.0.
> https://github.com/proximax-storage/js-xpx-chain-rest/releases/tag/release-v0.9.0

yeah, but why the [swagger-v0.7.2.yaml](https://github.com/proximax-storage/xpx-chain-devportal-docs/pull/75#diff-512aff36b0c025669f2694b0e8fa86dd6798ac76e967f54370295d3f09a73795) contains it?

**Comment by ynewmann** [comment]
Part of https://github.com/proximax-storage/xpx-chain-devportal-docs/pull/85

@wernling-proximax look at the PR above, please.

**Pull request closed without merging**
